"""Initial migration

Revision ID: 2a8d30c1e87a
Revises: 
Create Date: 2025-02-23 21:04:11.997369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8d30c1e87a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='02-23-2025 21:04:11', nullable=True),
    sa.Column('updated_at', sa.String(), server_default='02-23-2025 21:04:11', nullable=True),
    sa.PrimaryKeyConstraint('public_key')
    )
    op.create_table('users_sessions',
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('jwt', sa.String(), nullable=True),
    sa.Column('jwt_secret', sa.String(), nullable=True),
    sa.Column('signed_message', sa.String(), nullable=True),
    sa.Column('csrf_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='02-23-2025 21:04:11', nullable=True),
    sa.Column('updated_at', sa.String(), server_default='02-23-2025 21:04:11', nullable=True),
    sa.PrimaryKeyConstraint('public_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
