"""single chat db

Revision ID: febbc2f47b5d
Revises: 2a8d30c1e87a
Create Date: 2025-03-03 23:03:32.440031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febbc2f47b5d'
down_revision: Union[str, None] = '2a8d30c1e87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('singlechats',
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_key_user_initiator', sa.String(), nullable=False),
    sa.Column('public_key_user_receiver', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='03-03-2025 23:03:32', nullable=True),
    sa.Column('chat_accepted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('room_id', 'public_key_user_initiator', 'public_key_user_receiver')
    )
    op.create_index(op.f('ix_singlechats_room_id'), 'singlechats', ['room_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_singlechats_room_id'), table_name='singlechats')
    op.drop_table('singlechats')
    # ### end Alembic commands ###
